import { NewspaperTheme } from '@/types';

export const NEWSPAPER_THEMES: NewspaperTheme[] = [
  {
    id: 'classic-broadsheet',
    name: 'Classic Broadsheet',
    description: 'Timeless black & white, blackletter masthead — the gold standard of international broadsheet journalism',
    preview: { bg: '#faf9f6', text: '#0a0a0a', accent: '#0a0a0a' },
    mastheadFont: "'UnifrakturMaguntia', 'Old English Text MT', 'Engravers Old English BT', 'Cloister Black', 'Cinzel', Georgia, serif",
    headlineFont: "'Playfair Display', 'Times New Roman', Georgia, serif",
    bodyFont: "'IBM Plex Serif', Georgia, 'Times New Roman', serif",
    uiFont: "'Oswald', 'Arial Narrow', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Cinzel:wght@700;900&family=IBM+Plex+Serif:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Oswald:wght@500;600;700&family=Playfair+Display:ital,wght@0,600;0,700;0,800;0,900;1,400;1,700&family=UnifrakturMaguntia&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#faf9f6',
    inkColor: '#0a0a0a',
    accentColor: '#0a0a0a',
    categoryHeaderBg: '#0f172a',
    categoryHeaderText: '#ffffff',
    columnRuleColor: '#737373',
    mastheadBg: '#faf9f6',
    mastheadText: '#0a0a0a',
    mastheadStyle: 'blackletter',
    mastheadBorderStyle: 'triple-line',
    mastheadTagline: true,
    paperTexture: false,
    dropCapColor: '#0a0a0a',
    bylineDividerColor: '#737373',
    sectionBoxBorderTop: '2pt solid #0a0a0a',
  },
  {
    id: 'indian-express',
    name: 'Indian Express',
    description: 'Bold red accents, sharp serif hierarchy — authoritative national journalism',
    preview: { bg: '#ffffff', text: '#111827', accent: '#c0392b' },
    mastheadFont: "'Playfair Display', 'Times New Roman', Georgia, serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'Tinos', Georgia, 'Times New Roman', serif",
    uiFont: "'Oswald', 'Arial Narrow', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Tinos:ital,wght@0,400;0,700;1,400;1,700&family=Playfair+Display:ital,wght@0,600;0,700;0,800;0,900;1,400;1,700&family=Oswald:wght@500;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#ffffff',
    inkColor: '#111827',
    accentColor: '#c0392b',
    categoryHeaderBg: '#991b1b',
    categoryHeaderText: '#ffffff',
    columnRuleColor: '#9ca3af',
    mastheadBg: '#ffffff',
    mastheadText: '#111827',
    mastheadStyle: 'slab',
    mastheadBorderStyle: 'triple-line',
    mastheadTagline: true,
    paperTexture: false,
    dropCapColor: '#c0392b',
    bylineDividerColor: '#c0392b',
    sectionBoxBorderTop: '2pt solid #c0392b',
  },
  {
    id: 'times-of-india',
    name: 'Times of India',
    description: 'Warm newsprint paper, rich serif typography, subtle terracotta accents',
    preview: { bg: '#fbf6ec', text: '#1c1917', accent: '#b45309' },
    mastheadFont: "'Playfair Display', 'Times New Roman', Georgia, serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'Lora', Georgia, 'Times New Roman', serif",
    uiFont: "'Oswald', 'Arial Narrow', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,700&family=Playfair+Display:ital,wght@0,600;0,700;0,800;0,900;1,400;1,700&family=Oswald:wght@500;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#fbf6ec',
    inkColor: '#1c1917',
    accentColor: '#b45309',
    categoryHeaderBg: '#9a3412',
    categoryHeaderText: '#ffffff',
    columnRuleColor: '#d6c7b2',
    mastheadBg: '#fbf6ec',
    mastheadText: '#1c1917',
    mastheadStyle: 'bold',
    mastheadBorderStyle: 'ornate',
    mastheadTagline: true,
    paperTexture: true,
    dropCapColor: '#b45309',
    bylineDividerColor: '#b45309',
    sectionBoxBorderTop: '2pt solid #b45309',
  },
  {
    id: 'guardian-modern',
    name: 'Guardian Modern',
    description: 'Crisp white, deep royal navy accents, contemporary broadsheet balance',
    preview: { bg: '#ffffff', text: '#0f172a', accent: '#005689' },
    mastheadFont: "'Playfair Display', Georgia, serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'IBM Plex Serif', Georgia, serif",
    uiFont: "'Oswald', 'Arial Narrow', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Playfair+Display:ital,wght@0,600;0,700;0,800;0,900;1,400&family=Oswald:wght@500;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#ffffff',
    inkColor: '#0f172a',
    accentColor: '#005689',
    categoryHeaderBg: '#005689',
    categoryHeaderText: '#ffffff',
    columnRuleColor: '#cbd5e1',
    mastheadBg: '#ffffff',
    mastheadText: '#0f172a',
    mastheadStyle: 'modern',
    mastheadBorderStyle: 'minimal',
    mastheadTagline: true,
    paperTexture: false,
    dropCapColor: '#005689',
    bylineDividerColor: '#005689',
    sectionBoxBorderTop: '2pt solid #005689',
  },
  {
    id: 'mint-business',
    name: 'Mint Business',
    description: 'Subtle pale mint financial paper tint, forest green accents, refined data presentation',
    preview: { bg: '#f4f9f5', text: '#064e3b', accent: '#059669' },
    mastheadFont: "'Playfair Display', Georgia, serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'IBM Plex Serif', Georgia, serif",
    uiFont: "'Oswald', 'Arial Narrow', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Playfair+Display:ital,wght@0,600;0,700;0,800;0,900;1,400&family=Oswald:wght@500;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#f4f9f5',
    inkColor: '#064e3b',
    accentColor: '#059669',
    categoryHeaderBg: '#065f46',
    categoryHeaderText: '#ffffff',
    columnRuleColor: '#a7f3d0',
    mastheadBg: '#f4f9f5',
    mastheadText: '#064e3b',
    mastheadStyle: 'slab',
    mastheadBorderStyle: 'double',
    mastheadTagline: true,
    paperTexture: false,
    dropCapColor: '#059669',
    bylineDividerColor: '#059669',
    sectionBoxBorderTop: '2pt solid #059669',
  },
  {
    id: 'dark-edition',
    name: 'Dark Edition',
    description: 'Deep luxury dark slate paper, warm ivory body text, rich warm gold accents',
    preview: { bg: '#111827', text: '#f8fafc', accent: '#f59e0b' },
    mastheadFont: "'Playfair Display', Georgia, serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'IBM Plex Serif', Georgia, serif",
    uiFont: "'Oswald', 'Arial Narrow', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Playfair+Display:ital,wght@0,600;0,700;0,800;0,900;1,400&family=Oswald:wght@500;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#111827',
    inkColor: '#f8fafc',
    accentColor: '#f59e0b',
    categoryHeaderBg: '#1e293b',
    categoryHeaderText: '#f5c842',
    columnRuleColor: '#334155',
    mastheadBg: '#111827',
    mastheadText: '#f5c842',
    mastheadStyle: 'bold',
    mastheadBorderStyle: 'triple-line',
    mastheadTagline: true,
    paperTexture: false,
    dropCapColor: '#f5c842',
    bylineDividerColor: '#f5c842',
    sectionBoxBorderTop: '2pt solid #f5c842',
  },
];

export function getThemeById(id: string): NewspaperTheme {
  return NEWSPAPER_THEMES.find((t) => t.id === id) ?? NEWSPAPER_THEMES[0];
}
