import { NewspaperTheme } from '@/types';

export const NEWSPAPER_THEMES: NewspaperTheme[] = [
  {
    id: 'classic-broadsheet',
    name: 'Classic Broadsheet',
    description: 'Timeless black & white, blackletter masthead — the gold standard of print journalism',
    preview: { bg: '#ffffff', text: '#000000', accent: '#000000' },
    mastheadFont: "'UnifrakturMaguntia', serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'IBM Plex Serif', Georgia, 'Times New Roman', serif",
    uiFont: "'Oswald', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,400;0,500;0,700;1,400&family=Playfair+Display:wght@400;700;800;900&family=Oswald:wght@400;500;600;700&family=UnifrakturMaguntia&family=Tinos:ital,wght@0,400;0,700;1,400;1,700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#ffffff',
    inkColor: '#000000',
    accentColor: '#000000',
    categoryHeaderBg: '#1a1a1a',
    categoryHeaderText: '#ffffff',
    columnRuleColor: '#888888',
    mastheadBg: '#ffffff',
    mastheadText: '#000000',
    mastheadStyle: 'blackletter',
    mastheadBorderStyle: 'triple-line',
    mastheadTagline: true,
    paperTexture: false,
    dropCapColor: '#000000',
    bylineDividerColor: '#d41c1c',
    sectionBoxBorderTop: '2pt solid #000000',
  },
  {
    id: 'indian-express',
    name: 'Indian Express',
    description: 'Bold red accents, sharp edges — India\'s most trusted news authority',
    preview: { bg: '#fff8f8', text: '#1a1a1a', accent: '#c0392b' },
    mastheadFont: "'Playfair Display', Georgia, serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'Tinos', Georgia, serif",
    uiFont: "'Oswald', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Tinos:ital,wght@0,400;0,700;1,400;1,700&family=Playfair+Display:ital,wght@0,400;0,700;0,800;0,900;1,400&family=Oswald:wght@400;500;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#fefefe',
    inkColor: '#1a1a1a',
    accentColor: '#c0392b',
    categoryHeaderBg: '#c0392b',
    categoryHeaderText: '#ffffff',
    columnRuleColor: '#aaaaaa',
    mastheadBg: '#ffffff',
    mastheadText: '#1a1a1a',
    mastheadStyle: 'slab',
    mastheadBorderStyle: 'triple-line',
    mastheadTagline: true,
    paperTexture: false,
    dropCapColor: '#c0392b',
    bylineDividerColor: '#c0392b',
    sectionBoxBorderTop: '2pt solid #c0392b',
  },
  {
    id: 'times-of-india',
    name: 'Times of India',
    description: 'Warm newsprint tan, heavy serifs — the voice of a billion readers',
    preview: { bg: '#fdf8f0', text: '#1a0d00', accent: '#b5451b' },
    mastheadFont: "'Playfair Display', Georgia, serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'Lora', Georgia, serif",
    uiFont: "'Oswald', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,700&family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400&family=Oswald:wght@400;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#fdf8f0',
    inkColor: '#1a0d00',
    accentColor: '#b5451b',
    categoryHeaderBg: '#b5451b',
    categoryHeaderText: '#fff8f0',
    columnRuleColor: '#c8a97a',
    mastheadBg: '#fdf8f0',
    mastheadText: '#1a0d00',
    mastheadStyle: 'bold',
    mastheadBorderStyle: 'ornate',
    mastheadTagline: true,
    paperTexture: true,
    dropCapColor: '#b5451b',
    bylineDividerColor: '#b5451b',
    sectionBoxBorderTop: '2pt solid #b5451b',
  },
  {
    id: 'guardian-modern',
    name: 'Guardian Modern',
    description: 'Thin rules, deep blue accents — progressive journalism with impeccable design',
    preview: { bg: '#ffffff', text: '#121212', accent: '#005689' },
    mastheadFont: "'Playfair Display', Georgia, serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'IBM Plex Serif', Georgia, serif",
    uiFont: "'Oswald', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,400;0,500;0,700;1,400&family=Playfair+Display:ital,wght@0,400;0,700;0,800;0,900;1,400&family=Oswald:wght@400;500;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#ffffff',
    inkColor: '#121212',
    accentColor: '#005689',
    categoryHeaderBg: '#005689',
    categoryHeaderText: '#ffffff',
    columnRuleColor: '#cccccc',
    mastheadBg: '#005689',
    mastheadText: '#ffffff',
    mastheadStyle: 'modern',
    mastheadBorderStyle: 'minimal',
    mastheadTagline: false,
    paperTexture: false,
    dropCapColor: '#005689',
    bylineDividerColor: '#005689',
    sectionBoxBorderTop: '2pt solid #005689',
  },
  {
    id: 'mint-business',
    name: 'Mint Business',
    description: 'Forest green, financial precision — where data meets distinguished design',
    preview: { bg: '#f8fdf9', text: '#0a2518', accent: '#1a6b3c' },
    mastheadFont: "'Playfair Display', Georgia, serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'IBM Plex Serif', Georgia, serif",
    uiFont: "'Oswald', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,400;0,500;0,700;1,400&family=Playfair+Display:ital,wght@0,400;0,700;0,800;0,900;1,400&family=Oswald:wght@400;500;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#f8fdf9',
    inkColor: '#0a2518',
    accentColor: '#1a6b3c',
    categoryHeaderBg: '#1a6b3c',
    categoryHeaderText: '#ffffff',
    columnRuleColor: '#a8d5b5',
    mastheadBg: '#0a2518',
    mastheadText: '#f8fdf9',
    mastheadStyle: 'slab',
    mastheadBorderStyle: 'double',
    mastheadTagline: true,
    paperTexture: false,
    dropCapColor: '#1a6b3c',
    bylineDividerColor: '#1a6b3c',
    sectionBoxBorderTop: '2pt solid #1a6b3c',
  },
  {
    id: 'dark-edition',
    name: 'Dark Edition',
    description: 'Midnight press — bold gold on deep charcoal for the after-hours edition',
    preview: { bg: '#0f0f0f', text: '#f5f5f0', accent: '#f5c842' },
    mastheadFont: "'Playfair Display', Georgia, serif",
    headlineFont: "'Playfair Display', Georgia, serif",
    bodyFont: "'IBM Plex Serif', Georgia, serif",
    uiFont: "'Oswald', sans-serif",
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,400;0,500;0,700;1,400&family=Playfair+Display:ital,wght@0,400;0,700;0,800;0,900;1,400&family=Oswald:wght@400;500;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&display=swap',
    paperBg: '#0f0f0f',
    inkColor: '#f0ece0',
    accentColor: '#f5c842',
    categoryHeaderBg: '#1e1a00',
    categoryHeaderText: '#f5c842',
    columnRuleColor: '#3a3a3a',
    mastheadBg: '#0f0f0f',
    mastheadText: '#f5c842',
    mastheadStyle: 'bold',
    mastheadBorderStyle: 'triple-line',
    mastheadTagline: true,
    paperTexture: false,
    dropCapColor: '#f5c842',
    bylineDividerColor: '#f5c842',
    sectionBoxBorderTop: '2pt solid #f5c842',
  },
];

export function getThemeById(id: string): NewspaperTheme {
  return NEWSPAPER_THEMES.find((t) => t.id === id) ?? NEWSPAPER_THEMES[0];
}
